require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CookiesController do

  # This should return the minimal set of attributes required to create a valid
  # Cookie. As you add validations to Cookie, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "rescipe" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CookiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cookies as @cookies" do
      cookie = Cookie.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cookies).should eq([cookie])
    end
  end

  describe "GET show" do
    it "assigns the requested cookie as @cookie" do
      cookie = Cookie.create! valid_attributes
      get :show, {:id => cookie.to_param}, valid_session
      assigns(:cookie).should eq(cookie)
    end
  end

  describe "GET new" do
    it "assigns a new cookie as @cookie" do
      get :new, {}, valid_session
      assigns(:cookie).should be_a_new(Cookie)
    end
  end

  describe "GET edit" do
    it "assigns the requested cookie as @cookie" do
      cookie = Cookie.create! valid_attributes
      get :edit, {:id => cookie.to_param}, valid_session
      assigns(:cookie).should eq(cookie)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cookie" do
        expect {
          post :create, {:cookie => valid_attributes}, valid_session
        }.to change(Cookie, :count).by(1)
      end

      it "assigns a newly created cookie as @cookie" do
        post :create, {:cookie => valid_attributes}, valid_session
        assigns(:cookie).should be_a(Cookie)
        assigns(:cookie).should be_persisted
      end

      it "redirects to the created cookie" do
        post :create, {:cookie => valid_attributes}, valid_session
        response.should redirect_to(Cookie.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cookie as @cookie" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cookie.any_instance.stub(:save).and_return(false)
        post :create, {:cookie => { "rescipe" => "invalid value" }}, valid_session
        assigns(:cookie).should be_a_new(Cookie)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cookie.any_instance.stub(:save).and_return(false)
        post :create, {:cookie => { "rescipe" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cookie" do
        cookie = Cookie.create! valid_attributes
        # Assuming there are no other cookies in the database, this
        # specifies that the Cookie created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cookie.any_instance.should_receive(:update_attributes).with({ "rescipe" => "MyString" })
        put :update, {:id => cookie.to_param, :cookie => { "rescipe" => "MyString" }}, valid_session
      end

      it "assigns the requested cookie as @cookie" do
        cookie = Cookie.create! valid_attributes
        put :update, {:id => cookie.to_param, :cookie => valid_attributes}, valid_session
        assigns(:cookie).should eq(cookie)
      end

      it "redirects to the cookie" do
        cookie = Cookie.create! valid_attributes
        put :update, {:id => cookie.to_param, :cookie => valid_attributes}, valid_session
        response.should redirect_to(cookie)
      end
    end

    describe "with invalid params" do
      it "assigns the cookie as @cookie" do
        cookie = Cookie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cookie.any_instance.stub(:save).and_return(false)
        put :update, {:id => cookie.to_param, :cookie => { "rescipe" => "invalid value" }}, valid_session
        assigns(:cookie).should eq(cookie)
      end

      it "re-renders the 'edit' template" do
        cookie = Cookie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cookie.any_instance.stub(:save).and_return(false)
        put :update, {:id => cookie.to_param, :cookie => { "rescipe" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cookie" do
      cookie = Cookie.create! valid_attributes
      expect {
        delete :destroy, {:id => cookie.to_param}, valid_session
      }.to change(Cookie, :count).by(-1)
    end

    it "redirects to the cookies list" do
      cookie = Cookie.create! valid_attributes
      delete :destroy, {:id => cookie.to_param}, valid_session
      response.should redirect_to(cookies_url)
    end
  end

end
